/**
 * Trust Kernel v2 — levels, reason codes and CLI exit codes (spec/TRUST-KERNEL.md §7, §9).
 * Reason codes are part of the normative interface: the adversarial corpus asserts them, so every
 * implementation (JS, Python, …) MUST emit the same code for the same failure.
 */
export const KERNEL_ID = 'fractalai-trust-kernel/2';
export const SPEC_VERSION = '2.0.0';

/** Ordered verdict levels. Each level implies the ones before it except time_anchored/finalized, which
 * imply `authentic` (an anchor proves existence of signed bytes, independently of key trust). */
export const LEVELS = Object.freeze(['integrity', 'authentic', 'trusted', 'time_anchored', 'finalized']);

/** Default policy: a receipt is `valid` when it is authentic AND signed by a key the pinned roots authorize. */
export const DEFAULT_REQUIRE = Object.freeze(['integrity', 'authentic', 'trusted']);

/** CLI exit codes: 0 valid; 1x = first required level that failed; 2 usage; 3 input could not be read/parsed. */
export const EXIT = Object.freeze({
  VALID: 0, USAGE: 2, INPUT: 3,
  integrity: 10, authentic: 11, trusted: 12, time_anchored: 13, finalized: 14,
});

export const C = Object.freeze({
  // input hygiene
  JSON_INVALID: 'JSON_INVALID', JSON_DUPLICATE_KEY: 'JSON_DUPLICATE_KEY', JSON_TOO_DEEP: 'JSON_TOO_DEEP',
  JSON_TOO_LARGE: 'JSON_TOO_LARGE', JSON_LONE_SURROGATE: 'JSON_LONE_SURROGATE', INPUT_SHAPE: 'INPUT_SHAPE',
  B64_NONCANONICAL: 'B64_NONCANONICAL', KEY_SIZE: 'KEY_SIZE', SIG_SIZE: 'SIG_SIZE',
  SIGNED_JSON_NUMBER: 'SIGNED_JSON_NUMBER',
  // integrity (kind-specific binding)
  KIND_UNKNOWN: 'KIND_UNKNOWN', DOMAIN_MISMATCH: 'DOMAIN_MISMATCH', ALGORITHM: 'ALGORITHM',
  CONTENT_ID_MISMATCH: 'CONTENT_ID_MISMATCH', RECEIPT_ID_MISMATCH: 'RECEIPT_ID_MISMATCH',
  EXPECTED_ID_MISMATCH: 'EXPECTED_ID_MISMATCH', SIGNED_MESSAGE_MISMATCH: 'SIGNED_MESSAGE_MISMATCH',
  CANONICAL_MALFORMED: 'CANONICAL_MALFORMED', UNSIGNED_FIELD_MISMATCH: 'UNSIGNED_FIELD_MISMATCH',
  SIGNED_TIME_MALFORMED: 'SIGNED_TIME_MALFORMED', ROUTE_RESERVED: 'ROUTE_RESERVED', ROUTE_MALFORMED: 'ROUTE_MALFORMED',
  DIGEST_MALFORMED: 'DIGEST_MALFORMED', SCHEMA_MISMATCH: 'SCHEMA_MISMATCH',
  // authentic
  SIGNATURE_INVALID: 'SIGNATURE_INVALID',
  // trusted
  NO_TRUST_SOURCE: 'NO_TRUST_SOURCE', DIRECTORY_INVALID: 'DIRECTORY_INVALID', DIRECTORY_SIGNER_NOT_PINNED: 'DIRECTORY_SIGNER_NOT_PINNED',
  DIRECTORY_ROLLBACK: 'DIRECTORY_ROLLBACK', DIRECTORY_EQUIVOCATION: 'DIRECTORY_EQUIVOCATION', DIRECTORY_CHAIN_GAP: 'DIRECTORY_CHAIN_GAP',
  DIRECTORY_CHAIN_BREAK: 'DIRECTORY_CHAIN_BREAK', DIRECTORY_NOT_APPEND_ONLY: 'DIRECTORY_NOT_APPEND_ONLY',
  KEY_NOT_LISTED: 'KEY_NOT_LISTED', KEY_USE_MISMATCH: 'KEY_USE_MISMATCH', KEY_STATUS_RESERVED: 'KEY_STATUS_RESERVED',
  KEY_STATUS_UNKNOWN: 'KEY_STATUS_UNKNOWN', KEY_REVOKED: 'KEY_REVOKED', KEY_NOT_YET_VALID: 'KEY_NOT_YET_VALID',
  KEY_EXPIRED: 'KEY_EXPIRED', KEY_WINDOW_MALFORMED: 'KEY_WINDOW_MALFORMED', KEY_NEEDS_SIGNED_TIME: 'KEY_NEEDS_SIGNED_TIME',
  SIGNED_TIME_IN_FUTURE: 'SIGNED_TIME_IN_FUTURE', KEY_NOT_IN_PINNED_SET: 'KEY_NOT_IN_PINNED_SET',
  SELF_ATTEST_NOT_TRUSTED: 'SELF_ATTEST_NOT_TRUSTED',
  // time_anchored / finalized
  NO_ANCHOR: 'NO_ANCHOR', ANCHOR_REF_MALFORMED: 'ANCHOR_REF_MALFORMED', ANCHOR_CHAIN_NOT_PINNED: 'ANCHOR_CHAIN_NOT_PINNED',
  ANCHOR_CONTRACT_NOT_PINNED: 'ANCHOR_CONTRACT_NOT_PINNED', ANCHOR_CODEHASH_MISMATCH: 'ANCHOR_CODEHASH_MISMATCH',
  ANCHOR_WRONG_CHAIN: 'ANCHOR_WRONG_CHAIN', ANCHOR_NOT_FOUND: 'ANCHOR_NOT_FOUND', ANCHOR_AMBIGUOUS: 'ANCHOR_AMBIGUOUS',
  ANCHOR_TX_FAILED: 'ANCHOR_TX_FAILED', ANCHOR_LOG_REMOVED: 'ANCHOR_LOG_REMOVED', ANCHOR_LOG_MALFORMED: 'ANCHOR_LOG_MALFORMED',
  ANCHOR_SQUATTED: 'ANCHOR_SQUATTED', ANCHOR_KID_MISMATCH: 'ANCHOR_KID_MISMATCH', ANCHOR_BLOCK_MISMATCH: 'ANCHOR_BLOCK_MISMATCH',
  ANCHOR_TIME_MISMATCH: 'ANCHOR_TIME_MISMATCH', ANCHOR_OBSERVED_AT_MISMATCH: 'ANCHOR_OBSERVED_AT_MISMATCH',
  ANCHOR_FORWARD_DATED: 'ANCHOR_FORWARD_DATED', ANCHOR_CONFIRMATIONS: 'ANCHOR_CONFIRMATIONS',
  ANCHOR_REQUIRES_SIGNED_TIME: 'ANCHOR_REQUIRES_SIGNED_TIME', ANCHOR_TESTNET_NOT_ALLOWED: 'ANCHOR_TESTNET_NOT_ALLOWED',
  ANCHOR_ANCHORER_UNKNOWN: 'ANCHOR_ANCHORER_UNKNOWN', ANCHOR_NO_RPC: 'ANCHOR_NO_RPC', RPC_ERROR: 'RPC_ERROR',
  RPC_DISAGREEMENT: 'RPC_DISAGREEMENT', RPC_QUORUM: 'RPC_QUORUM',
  SOL_GENESIS_MISMATCH: 'SOL_GENESIS_MISMATCH', SOL_NO_BLOCKTIME: 'SOL_NO_BLOCKTIME', SOL_NOT_FINALIZED: 'SOL_NOT_FINALIZED',
  SOL_STATUS_SLOT: 'SOL_STATUS_SLOT', SOL_TX_MALFORMED: 'SOL_TX_MALFORMED', SOL_SIGNATURE_MISMATCH: 'SOL_SIGNATURE_MISMATCH',
  SOL_ED25519_INVALID: 'SOL_ED25519_INVALID', SOL_SIGNER_NOT_ANNOUNCED: 'SOL_SIGNER_NOT_ANNOUNCED',
  SOL_LOOKUP_TABLES: 'SOL_LOOKUP_TABLES', SOL_INSTRUCTION_COUNT: 'SOL_INSTRUCTION_COUNT', SOL_NOT_MEMO: 'SOL_NOT_MEMO',
  SOL_MEMO_SIGNER: 'SOL_MEMO_SIGNER', SOL_MEMO_MISMATCH: 'SOL_MEMO_MISMATCH', SOL_SIGNER_COUNT: 'SOL_SIGNER_COUNT',
  NOT_FINALIZED: 'NOT_FINALIZED',
  KIND_AMBIGUOUS: 'KIND_AMBIGUOUS', KIND_NOT_ALLOWED: 'KIND_NOT_ALLOWED',
  ENGINE_SELFTEST_FAILED: 'ENGINE_SELFTEST_FAILED', ENGINE_UNSAFE_OBJECT_INPUT: 'ENGINE_UNSAFE_OBJECT_INPUT',
  SNAPSHOT_MISMATCH: 'SNAPSHOT_MISMATCH',
  INTERNAL: 'INTERNAL',
});

/** A coded failure. Kernel code throws KernelError; the decision layer turns it into a reason. */
export class KernelError extends Error {
  constructor(code, detail) {
    super(`${code}: ${detail}`);
    this.code = code;
    this.detail = detail;
  }
}
export const fail = (code, detail) => { throw new KernelError(code, detail); };
